language: cpp

git:
  depth: 1

os:
  - linux
# - osx

branches:
  only:
    - main
    - devel

compiler:
  - gcc

matrix:
  include:
    - os: linux
      dist: bionic
      env:
        - BUILD="qmake" GMIC_HOST="all"
    - os: linux
      dist: focal
      env:
        - BUILD="qmake" GMIC_HOST="all"

  fast_finish: true


before_install:
  - date -u
  - uname -a

install:
  - if [ -z "$TRAVIS_OS_NAME" -o "$TRAVIS_OS_NAME" = "linux" ]; then
       sudo apt-get install --allow-unauthenticated gdb qt5-default qt5-qmake \
       qttools5-dev qttools5-dev-tools;
    fi;

script:
  - g++ --version
  - if [ -z "$TRAVIS_OS_NAME" -o "$TRAVIS_OS_NAME" = "linux" ]; then
       travis_wait 45 ./scripts/travis_build_${BUILD}.sh;
    fi;
